export default [
  "What goes up and down but does not move? Stairs.",
  "Where should a 500 pound alien go? On a diet.",
  "What did one toilet say to the other? you look flushed.",
  "What did one wall say to the other wall? I'll meet you at the corner.",
  "Can a kangaroo jump higher than a house? Of course, a house doesn’t jump at all.",
  "What is the difference between a snowman and a snowwoman? Snowballs.",
  "Men 1845: I just killed a buffalo. Men 1952: I just fixed the roof. Men 2017: I just shaved my legs.",
  "I Googled \"how to start a wildfire\". I got over 40,000 matches.",
  "What’s the biggest pan in the world? Japan.",
  "What do snowmen do in their spare time? Just chilling",
  "What lies on the ocean bed and is twitching uncontrollably? A nervous wreck.",
  "How do you make holy water? Boil the hell out of it.",
  "Don't make fun of fat people. They've got enough on their plate as it is.",
  "One pen to the other: You are INKredible.",
  "I don’t want to cut my hair! I’m really attached to it!",
  "I wanted to tell you a joke about leeches. But I won’t – they all suck.",
  "Han Solo married princess Leia. From then on he was Han Married.",
  "Cemeteries are so popular, people are just dying to get in there.",
  "What do lawyers wear to court? Lawsuits.",
  "How do you drown a hipster? In the mainstream.",
  "What did the tie say to the hat? Go on ahead and I'll hang around",
  "How difficult is it to seduce a fat woman? Piece of cake.",
  "What did the ocean say to the beach? Nothing, it just waved.",
  "Two snowmen are standing in a field. One says to the other : \"Funny, I smell carrots too\"."
]